<?php
// Stores the "preferred" post type of each category.
// E.g.
$categories_post_types = [
    // Wellbeing
    ["categoryid"=>"1159" , "post_type"=>"post", "name"=>"All Wellbeing"],
    ["categoryid"=>"1160" , "post_type"=>"post", "name"=>"Exercise"],
    ["categoryid"=>"1161" , "post_type"=>"post", "name"=>"Food &amp; Nutrition"],
    ["categoryid"=>"1166" , "post_type"=>"post", "name"=>"Healthy Body"],
    ["categoryid"=>"1167" , "post_type"=>"post", "name"=>"Healthy Mind"],
    ["categoryid"=>"1168" , "post_type"=>"post", "name"=>"Sex &amp; Relationships"],
    ["categoryid"=>"1169" , "post_type"=>"post", "name"=>"Skincare &amp; Haircare"],
    ["categoryid"=>"1170" , "post_type"=>"post", "name"=>"Travel"],
    // Fertility
    ["categoryid"=>"1164" , "post_type"=>"post", "name"=>"All Fertility"],
    ["categoryid"=>"1171" , "post_type"=>"post", "name"=>"Donor Conception"],
    ["categoryid"=>"1172" , "post_type"=>"post", "name"=>"Health &amp; Nutrition"],
    ["categoryid"=>"1173" , "post_type"=>"post", "name"=>"Preservation"],
    ["categoryid"=>"1174" , "post_type"=>"post", "name"=>"Signs &amp; Symptoms"],
    ["categoryid"=>"1175" , "post_type"=>"post", "name"=>"Testing"],
    ["categoryid"=>"1176" , "post_type"=>"post", "name"=>"Holistic Support"],
    ["categoryid"=>"1177" , "post_type"=>"post", "name"=>"Causes &amp; Treatment"],
    ["categoryid"=>"1178" , "post_type"=>"post", "name"=>"LGBTQ+"],
    ["categoryid"=>"1179" , "post_type"=>"post", "name"=>"Male Fertility"],
    ["categoryid"=>"1180" , "post_type"=>"post", "name"=>"Miscarriage &amp; Recurrent Pregnancy Loss"],
    ["categoryid"=>"1181" , "post_type"=>"post", "name"=>"Natural Conception"],
    ["categoryid"=>"1182" , "post_type"=>"post", "name"=>"Solo Parenting"],
    ["categoryid"=>"1183" , "post_type"=>"post", "name"=>"Surrogacy"],
    ["categoryid"=>"1216" , "post_type"=>"post", "name"=>"Celebrity Stories"],
    //
    // ["categoryid"=>"1210" , "post_type"=>"post", "name"=>"Newborn &amp; Baby"],
    // ["categoryid"=>"1211" , "post_type"=>"post", "name"=>"Breastfeeding"],
    // ["categoryid"=>"1212" , "post_type"=>"post", "name"=>"Child"],
    // ["categoryid"=>"1213" , "post_type"=>"post", "name"=>"Pre-Teen"],
    // ["categoryid"=>"1214" , "post_type"=>"post", "name"=>"Teen"],
    // ["categoryid"=>"1215" , "post_type"=>"post", "name"=>"Adult &amp; Empty Nest"],
    // Pregnancy
	["categoryid"=>"1165", "post_type"=>"post", "name"=>"All Pregnancy"],
	["categoryid"=>"1184", "post_type"=>"post", "name"=>"A Dad’s Guide to Pregnancy"],
	["categoryid"=>"1185", "post_type"=>"post", "name"=>"Baby Names"],
	["categoryid"=>"1186", "post_type"=>"post", "name"=>"Birth &amp; Delivery"],
	["categoryid"=>"1187", "post_type"=>"post", "name"=>"Due Date Calculator"],
	["categoryid"=>"1188", "post_type"=>"post", "name"=>"Postpartum"],
    ["categoryid"=>"1189", "post_type"=>"post", "name"=>"Health &amp; Nutrition"],
	["categoryid"=>"1190", "post_type"=>"post", "name"=>"Loss &amp; Miscarriage"],
	["categoryid"=>"1191", "post_type"=>"post", "name"=>"Symptoms"],
	["categoryid"=>"1192", "post_type"=>"post", "name"=>"Preparing for a Baby"],
	["categoryid"=>"1193", "post_type"=>"post", "name"=>"Surrogacy Pregnancy"],
	["categoryid"=>"1194", "post_type"=>"post", "name"=>"Week by Week"],
    ["categoryid"=>"1207", "post_type"=>"post", "name"=>"First Trimester (weeks 1-12)"],
    ["categoryid"=>"1208", "post_type"=>"post", "name"=>"Second Trimester (weeks 13-26)"],
    ["categoryid"=>"1209", "post_type"=>"post", "name"=>"Third Trimester (weeks 27-birth)"],
    // Parenting
    ["categoryid"=>"1163" , "post_type"=>"post", "name"=>"All Parenting"],
    ["categoryid"=>"1196" , "post_type"=>"post", "name"=>"Activities with Kids"],
    ["categoryid"=>"1197" , "post_type"=>"post", "name"=>"Adoption &amp; Fostering"],
    ["categoryid"=>"1198" , "post_type"=>"post", "name"=>"Child Health &amp; Nutrition"],
    ["categoryid"=>"1199" , "post_type"=>"post", "name"=>"Child Loss &amp; Grief"],
    ["categoryid"=>"1200" , "post_type"=>"post", "name"=>"Divorce &amp; Separation"],
    ["categoryid"=>"1201" , "post_type"=>"post", "name"=>"Donor-Conceived Children"],
    ["categoryid"=>"1202" , "post_type"=>"post", "name"=>"Family Finances"],
    ["categoryid"=>"1203" , "post_type"=>"post", "name"=>"School &amp; Education"],
    ["categoryid"=>"1205" , "post_type"=>"post", "name"=>"Special Needs"],
    ["categoryid"=>"1206" , "post_type"=>"post", "name"=>"Surrogacy-Conceived Children"],
    // Experts
    ["categoryid"=>"1159" , "post_type"=>"expert_profiles" , "name"=>"Wellbeing"],
    ["categoryid"=>"1164" , "post_type"=>"expert_profiles" , "name"=>"Fertility"],
    ["categoryid"=>"1163" , "post_type"=>"expert_profiles" , "name"=>"Parenting"],
    ["categoryid"=>"1165" , "post_type"=>"expert_profiles" , "name"=>"Pregnancy"],
    // Watch & Listen
    ["categoryid"=>"1159" , "post_type"=>"videos" , "name"=>"Wellbeing Videos"],
    ["categoryid"=>"1164" , "post_type"=>"videos" , "name"=>"Fertility Videos"],
    ["categoryid"=>"1165" , "post_type"=>"videos" , "name"=>"Pregnancy Videos"],
    ["categoryid"=>"1163" , "post_type"=>"videos" , "name"=>"Parenting Videos"],
];